add oAuth
HansenBerlin/ThreeDeeFrontend pull request #11
Opened 2023-03-23 20:24 UTC by NicoSteinmueller

2023-03-23 22:41 UTC, HansenBerlin requested changes

2023-03-23 22:41 UTC, HansenBerlin commented on ThreeDeeFrontend/Program.cs
Der redundante Code sollte noch in einen Setupservice ausgelagert werden. Die program.cs sollte kurz und knapp die Services registrieren und weitestgehend frei von Boilerplate sein.

2023-03-23 22:41 UTC, HansenBerlin commented on ThreeDeeFrontend/ThreeDeeFrontend.csproj
Jetzt haben wir doch OAuth drin. Wir sollten m.E. nur OAuth2 nutzen. Klasse statt Masse,

2023-03-23 23:00 UTC, Gabriel-Mandtler commented
Ist mir to much und verstehe gefühlt nichts im Code :D. nicht so schlimm, Ihr macht das schon^^

2023-03-24 00:46 UTC, HansenBerlin commented
> Ist mir to much und verstehe gefühlt nichts im Code :D. nicht so schlimm, Ihr macht das schon^^

Ist fast 100% Templatecode der Standardauth von MS, also CopyPaste. Also mach dir keinen Kopp. Haben wir uns nicht ausgedacht und hätteste mit bisschen Support auch geschafft. 😁

2023-03-27 07:34 UTC, merged