Feature/api connection
HansenBerlin/ThreeDeeFrontend pull request #15
Opened 2023-04-11 21:54 UTC by NicoSteinmueller

2023-04-12 08:45 UTC, HansenBerlin requested changes

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeApplication/Models/PrintModel.cs
In Req/Response Models immer default values für nullables, außer null ist explizit gewollt

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Components/GCodeTable.razor.cs
> +    private IRepository<GCodeSettingsModel, GCodeSettingsModel> GCodeSettingsRepository { get; set; }
Wir müssen zwischen Request und Responsemodel unterscheiden (wenn es einen gibt, meistens schon) und die Models in Application nicht damit verwechseln. Lass erstmal so, ggfs ändert sich an der API Spec noch bisschen und ich würde eh nochmal ne Runde drehen und die Architektur aufräumen. Also MVVM und richtige Req/Response Models. Aber nur FYI (Model in MVVM != Model aus Repository und != Model in MVC)

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Components/GCodeTable.razor.cs
> +    private IEnumerable<GCodeSettingsModel> _gCodes = new List<GCodeSettingsModel>();
Vor und Nachteile hinsichtlich Performance von List und IEnum berücksichtigen. Einmal initialisieren und selten iterieren? -> IEnum. Öfter sortieren/itierieren/ändern -> List
Bei uns hat das keine Auswirkung, aber FYI (IEnum ist nicht immer "besser")

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Components/GCodeTable.razor.cs
> +            _gCodes = await GCodeSettingsRepository.GetAll(Id.ToString());
👍🏼

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Pages/FileCard.razor.cs
> +   [Inject] public IRepository<FileModelComplete, FileModelComplete> FileRepository { get; set; } = default!;
Naming FileModelComplete (was soll das sein - complete?) und nullable warning suppression (aua). Zudem weil injected nicht notwendig

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Pages/FileCard.razor.cs
>      {
Entweder in OnAfterRenderAsync odr selbst nen isInit bool setzen. Wird sonst mehrmals aufgerufen.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/Program.cs
> +builder.Services.AddSingleton<IEndpointService, EndpointService>();
Repositorys können auch als Singleton rein. Sind ja stateless bzw haben keinerlei shared state.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/ViewModels/FilesGridViewModel.cs
> +    [Inject] public IRepository<FileModel, FileModel> FileRepository { get; set; } = default!;
s.o. nullable suppression nicht nötig. 2 Repositories in einer Komponente deuten auf Code Smell hin. Zumal auch die Filemodel Namen dasselbe anzeigen. Würde nochmal überlegen wie das besser geht. Wir haben in den Routen eine File Ressource, ergo auch ein FileModel (bzw 2 wenn Request und Response) und nicht 3.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/ViewModels/FilesGridViewModel.cs
> +    [Inject] public IRepository<FileModelPrivate, FileModelPrivate> FileRepositoryPrivate { get; set; } = default!;
warum inject und public? It doch ne Standardklasse. Vrauchst du da nicht, reicht normale Konstruktorinjction.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeFrontend/ViewModels/FilesGridViewModel.cs
>          FileAccessStatus = newStatus;
mach mal dickes todo dran damit wir das nicht vergessen. ;-)

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/Repositories/Repository.cs
> +    protected readonly string Uri;
Da wir von der Klasse nicht erben können die private statt protected. Hatte ich in Dannys Repo nur so gemacht weil er die Klasse noch erweitert.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/Repositories/Repository.cs
> +    protected string ExtractQuery(Dictionary<string, string>? queries)
raus

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/ResourceUrls.cs
👍🏼

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/ResponseModels/FileModelComplete.cs
? Dead Code

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/ResponseModels/FileModelPrivate.cs
YAGNI

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/ResponseModels/GCodeSettingsModel.cs
> +    public double SuccessPercentage => Math.Round((double)SuccessfulPrints / (FailedPrints + SuccessfulPrints), 2);
da du das als req/response model nutzt (hatte es für nen anderen zweck gebaut, als Model in MVVM) gehört hier keine Logik rein.

2023-04-12 08:45 UTC, HansenBerlin commented on ThreeDeeInfrastructure/Services/EndpointService.cs
Konstruktr wieder rein und mit den entsprechenden Keys aus der appsettings bzw erwarteter Umgebungsvariable belegen. Wir können die Basisurl ja nicht im Code verdrahten

2023-04-12 11:49 UTC, NicoSteinmueller commented on ThreeDeeInfrastructure/ResponseModels/FileModelComplete.cs
TODO

2023-04-12 11:51 UTC, NicoSteinmueller commented on ThreeDeeInfrastructure/ResponseModels/GCodeSettingsModel.cs
> +    public double SuccessPercentage => Math.Round((double)SuccessfulPrints / (FailedPrints + SuccessfulPrints), 2);
einmal in der Komponente berechnen

2023-04-12 11:52 UTC, NicoSteinmueller commented on ThreeDeeInfrastructure/Services/EndpointService.cs
TODO ran

2023-04-12 13:53 UTC, NicoSteinmueller commented on ThreeDeeFrontend/Pages/FileCard.razor.cs
>      {
geht im zusammenspiel mit den anderen Komponenten nicht

2023-04-12 22:55 UTC, merged

2023-04-14 23:38 UTC, HansenBerlin commented on ThreeDeeFrontend/Pages/FileCard.razor.cs
>      {
hab ich übersehen die antwort. klar geht das.